# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09ea5d0732ab2b9d1d083279d732a2fef5c49374c4fe73705ec03739f02aeef878c45de6a424fe8fdaab2c0107a411d2978f8b0f94bc8120375758a23cd452a0

test:
  secret_key_base: 00f7bfe5fa9545d102b1834703f80035bf2aa7d0110f724d309d9a4c9b4d11e25d3946889ced266aa24b70fa8ec85e61ad6274a15105d4d32f966a5ae0597693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
